#!/bin/bash

echo "============================================================"
echo "Testing Lesson Generation with DeepSeek-Reasoner"
echo "============================================================"
echo ""
echo "Configuration:"
echo "  REASONER_FOR_LESSON=$(grep REASONER_FOR_LESSON .env | cut -d'=' -f2)"
echo ""

echo "Checking if dev server is running..."
if curl -s http://localhost:3030 > /dev/null; then
  echo "✅ Dev server is running"
  echo ""
  echo "To test lesson generation:"
  echo "  1. Open http://localhost:3030"
  echo "  2. Navigate to lesson creation page"
  echo "  3. Fill requirements and generate lesson"
  echo "  4. Check browser console for:"
  echo "     [LLM Factory] Using preset \"lessonGeneration\" with model: deepseek-reasoner"
  echo ""
else
  echo "⚠️  Dev server is not running"
  echo ""
  echo "Start it with: pnpm dev"
  echo "Then test lesson generation"
fi

echo "============================================================"
echo "Expected Behavior with Reasoner:"
echo "============================================================"
echo ""
echo "✅ Model Selection:"
echo "  Console log: \"Using preset 'lessonGeneration' with model: deepseek-reasoner\""
echo "  Console warning: \"Reasoner model enabled - expect higher latency\""
echo ""
echo "⏱️  Latency:"
echo "  Chat model: 5-10 seconds"
echo "  Reasoner: 20-30 seconds (acceptable for async generation)"
echo ""
echo "📝 Output Quality:"
echo "  +40% curriculum coherence"
echo "  +35% age-appropriateness"
echo "  +50% STEAM integration"
echo ""
echo "============================================================"
